/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.ide;

import org.xtext.assignment3.msdsl.ide.AbstractMSDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MSDslIdeModule extends AbstractMSDslIdeModule {
}
