/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.assignment3.msdsl.MSDslRuntimeModule;
import org.xtext.assignment3.msdsl.MSDslStandaloneSetup;
import org.xtext.assignment3.msdsl.ide.MSDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MSDslIdeSetup extends MSDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MSDslRuntimeModule _mSDslRuntimeModule = new MSDslRuntimeModule();
    MSDslIdeModule _mSDslIdeModule = new MSDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mSDslRuntimeModule, _mSDslIdeModule));
  }
}
