/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.validation;

import org.xtext.assignment3.msdsl.validation.AbstractMSDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MSDslValidator extends AbstractMSDslValidator {
}
