/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl;

import org.xtext.assignment3.msdsl.AbstractMSDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MSDslRuntimeModule extends AbstractMSDslRuntimeModule {
}
