/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl;

import org.xtext.assignment3.msdsl.MSDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MSDslStandaloneSetup extends MSDslStandaloneSetupGenerated {
  public static void doSetup() {
    new MSDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
