/*
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMSDslScopeProvider extends DelegatingScopeProvider {
}
