/*
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.assignment3.msdsl.parser.antlr.internal.InternalMSDslParser;
import org.xtext.assignment3.msdsl.services.MSDslGrammarAccess;

public class MSDslParser extends AbstractAntlrParser {

	@Inject
	private MSDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMSDslParser createParser(XtextTokenStream stream) {
		return new InternalMSDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ManufacturingSystem";
	}

	public MSDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MSDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
