/*
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.assignment3.msdsl.ide.contentassist.antlr.internal.InternalMSDslParser;
import org.xtext.assignment3.msdsl.services.MSDslGrammarAccess;

public class MSDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MSDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MSDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getManufacturingSystemElementAccess().getAlternatives(), "rule__ManufacturingSystemElement__Alternatives");
			builder.put(grammarAccess.getInputConditionAccess().getAlternatives(), "rule__InputCondition__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBinaryTypeAccess().getAlternatives(), "rule__BinaryType__Alternatives");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup(), "rule__ManufacturingSystem__Group__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_6(), "rule__ManufacturingSystem__Group_6__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_11(), "rule__ManufacturingSystem__Group_11__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_13(), "rule__ManufacturingSystem__Group_13__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_17(), "rule__ManufacturingSystem__Group_17__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_19(), "rule__ManufacturingSystem__Group_19__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_19_3(), "rule__ManufacturingSystem__Group_19_3__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_20(), "rule__ManufacturingSystem__Group_20__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_20_3(), "rule__ManufacturingSystem__Group_20_3__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_21(), "rule__ManufacturingSystem__Group_21__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_21_3(), "rule__ManufacturingSystem__Group_21_3__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup(), "rule__ManufacturingSystemElement_Impl__Group__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup_4(), "rule__ManufacturingSystemElement_Impl__Group_4__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup_4_2(), "rule__ManufacturingSystemElement_Impl__Group_4_2__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup_5(), "rule__ManufacturingSystemElement_Impl__Group_5__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup(), "rule__StoragePoint__Group__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_4(), "rule__StoragePoint__Group_4__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_4_2(), "rule__StoragePoint__Group_4_2__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_5(), "rule__StoragePoint__Group_5__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_6(), "rule__StoragePoint__Group_6__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_6_3(), "rule__StoragePoint__Group_6_3__0");
			builder.put(grammarAccess.getWorkPieceTypeAccess().getGroup(), "rule__WorkPieceType__Group__0");
			builder.put(grammarAccess.getWorkPieceAccess().getGroup(), "rule__WorkPiece__Group__0");
			builder.put(grammarAccess.getResponsibleAccess().getGroup(), "rule__Responsible__Group__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup(), "rule__ManufacturingStep__Group__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_3(), "rule__ManufacturingStep__Group_3__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_4(), "rule__ManufacturingStep__Group_4__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_4_2(), "rule__ManufacturingStep__Group_4_2__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_5(), "rule__ManufacturingStep__Group_5__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_9(), "rule__ManufacturingStep__Group_9__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_14(), "rule__ManufacturingStep__Group_14__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup(), "rule__TransportStep__Group__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_3(), "rule__TransportStep__Group_3__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_4(), "rule__TransportStep__Group_4__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_4_2(), "rule__TransportStep__Group_4_2__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_5(), "rule__TransportStep__Group_5__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_9(), "rule__TransportStep__Group_9__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_14(), "rule__TransportStep__Group_14__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup(), "rule__QualityAssuranceStep__Group__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_3(), "rule__QualityAssuranceStep__Group_3__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_4(), "rule__QualityAssuranceStep__Group_4__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_4_2(), "rule__QualityAssuranceStep__Group_4_2__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_5(), "rule__QualityAssuranceStep__Group_5__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_9(), "rule__QualityAssuranceStep__Group_9__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_14(), "rule__QualityAssuranceStep__Group_14__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup(), "rule__CompositeManufacturingStep__Group__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_3(), "rule__CompositeManufacturingStep__Group_3__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_4(), "rule__CompositeManufacturingStep__Group_4__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_4_2(), "rule__CompositeManufacturingStep__Group_4_2__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_5(), "rule__CompositeManufacturingStep__Group_5__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_9(), "rule__CompositeManufacturingStep__Group_9__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_14(), "rule__CompositeManufacturingStep__Group_14__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getInputCondition_ImplAccess().getGroup(), "rule__InputCondition_Impl__Group__0");
			builder.put(grammarAccess.getOutputDecisionAccess().getGroup(), "rule__OutputDecision__Group__0");
			builder.put(grammarAccess.getOutputDecisionAccess().getGroup_1(), "rule__OutputDecision__Group_1__0");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getGroup(), "rule__WorkPieceCondition__Group__0");
			builder.put(grammarAccess.getBinaryConditionAccess().getGroup(), "rule__BinaryCondition__Group__0");
			builder.put(grammarAccess.getNegationAccess().getGroup(), "rule__Negation__Group__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getNameAssignment_1(), "rule__ManufacturingSystem__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStartAssignment_5(), "rule__ManufacturingSystem__StartAssignment_5");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStartAssignment_6_1(), "rule__ManufacturingSystem__StartAssignment_6_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getEndAssignment_10(), "rule__ManufacturingSystem__EndAssignment_10");
			builder.put(grammarAccess.getManufacturingSystemAccess().getEndAssignment_11_1(), "rule__ManufacturingSystem__EndAssignment_11_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getResponsibleAssignment_13_1(), "rule__ManufacturingSystem__ResponsibleAssignment_13_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getConsistsOfAssignment_16(), "rule__ManufacturingSystem__ConsistsOfAssignment_16");
			builder.put(grammarAccess.getManufacturingSystemAccess().getConsistsOfAssignment_17_1(), "rule__ManufacturingSystem__ConsistsOfAssignment_17_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getUsesAssignment_19_2(), "rule__ManufacturingSystem__UsesAssignment_19_2");
			builder.put(grammarAccess.getManufacturingSystemAccess().getUsesAssignment_19_3_1(), "rule__ManufacturingSystem__UsesAssignment_19_3_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getTransformsAssignment_20_2(), "rule__ManufacturingSystem__TransformsAssignment_20_2");
			builder.put(grammarAccess.getManufacturingSystemAccess().getTransformsAssignment_20_3_1(), "rule__ManufacturingSystem__TransformsAssignment_20_3_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStaffAssignment_21_2(), "rule__ManufacturingSystem__StaffAssignment_21_2");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStaffAssignment_21_3_1(), "rule__ManufacturingSystem__StaffAssignment_21_3_1");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getNameAssignment_2(), "rule__ManufacturingSystemElement_Impl__NameAssignment_2");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getTransitionAssignment_4_1(), "rule__ManufacturingSystemElement_Impl__TransitionAssignment_4_1");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getTransitionAssignment_4_2_1(), "rule__ManufacturingSystemElement_Impl__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getResponsibleAssignment_5_1(), "rule__ManufacturingSystemElement_Impl__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getStoragePointAccess().getNameAssignment_2(), "rule__StoragePoint__NameAssignment_2");
			builder.put(grammarAccess.getStoragePointAccess().getTransitionAssignment_4_1(), "rule__StoragePoint__TransitionAssignment_4_1");
			builder.put(grammarAccess.getStoragePointAccess().getTransitionAssignment_4_2_1(), "rule__StoragePoint__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getStoragePointAccess().getResponsibleAssignment_5_1(), "rule__StoragePoint__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getStoragePointAccess().getStoresAssignment_6_2(), "rule__StoragePoint__StoresAssignment_6_2");
			builder.put(grammarAccess.getStoragePointAccess().getStoresAssignment_6_3_1(), "rule__StoragePoint__StoresAssignment_6_3_1");
			builder.put(grammarAccess.getWorkPieceTypeAccess().getNameAssignment_1(), "rule__WorkPieceType__NameAssignment_1");
			builder.put(grammarAccess.getWorkPieceAccess().getHasTypeAssignment_3(), "rule__WorkPiece__HasTypeAssignment_3");
			builder.put(grammarAccess.getResponsibleAccess().getNameAssignment_1(), "rule__Responsible__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getNameAssignment_1(), "rule__ManufacturingStep__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getSpeedAssignment_3_1(), "rule__ManufacturingStep__SpeedAssignment_3_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getTransitionAssignment_4_1(), "rule__ManufacturingStep__TransitionAssignment_4_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getTransitionAssignment_4_2_1(), "rule__ManufacturingStep__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getResponsibleAssignment_5_1(), "rule__ManufacturingStep__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getInputAssignment_8(), "rule__ManufacturingStep__InputAssignment_8");
			builder.put(grammarAccess.getManufacturingStepAccess().getInputAssignment_9_1(), "rule__ManufacturingStep__InputAssignment_9_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getOutputAssignment_13(), "rule__ManufacturingStep__OutputAssignment_13");
			builder.put(grammarAccess.getManufacturingStepAccess().getOutputAssignment_14_1(), "rule__ManufacturingStep__OutputAssignment_14_1");
			builder.put(grammarAccess.getTransportStepAccess().getNameAssignment_1(), "rule__TransportStep__NameAssignment_1");
			builder.put(grammarAccess.getTransportStepAccess().getSpeedAssignment_3_1(), "rule__TransportStep__SpeedAssignment_3_1");
			builder.put(grammarAccess.getTransportStepAccess().getTransitionAssignment_4_1(), "rule__TransportStep__TransitionAssignment_4_1");
			builder.put(grammarAccess.getTransportStepAccess().getTransitionAssignment_4_2_1(), "rule__TransportStep__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getTransportStepAccess().getResponsibleAssignment_5_1(), "rule__TransportStep__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getTransportStepAccess().getInputAssignment_8(), "rule__TransportStep__InputAssignment_8");
			builder.put(grammarAccess.getTransportStepAccess().getInputAssignment_9_1(), "rule__TransportStep__InputAssignment_9_1");
			builder.put(grammarAccess.getTransportStepAccess().getOutputAssignment_13(), "rule__TransportStep__OutputAssignment_13");
			builder.put(grammarAccess.getTransportStepAccess().getOutputAssignment_14_1(), "rule__TransportStep__OutputAssignment_14_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getNameAssignment_1(), "rule__QualityAssuranceStep__NameAssignment_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getSpeedAssignment_3_1(), "rule__QualityAssuranceStep__SpeedAssignment_3_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getTransitionAssignment_4_1(), "rule__QualityAssuranceStep__TransitionAssignment_4_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getTransitionAssignment_4_2_1(), "rule__QualityAssuranceStep__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getResponsibleAssignment_5_1(), "rule__QualityAssuranceStep__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getInputAssignment_8(), "rule__QualityAssuranceStep__InputAssignment_8");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getInputAssignment_9_1(), "rule__QualityAssuranceStep__InputAssignment_9_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getOutputAssignment_13(), "rule__QualityAssuranceStep__OutputAssignment_13");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getOutputAssignment_14_1(), "rule__QualityAssuranceStep__OutputAssignment_14_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getNameAssignment_1(), "rule__CompositeManufacturingStep__NameAssignment_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getSpeedAssignment_3_1(), "rule__CompositeManufacturingStep__SpeedAssignment_3_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getTransitionAssignment_4_1(), "rule__CompositeManufacturingStep__TransitionAssignment_4_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getTransitionAssignment_4_2_1(), "rule__CompositeManufacturingStep__TransitionAssignment_4_2_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getResponsibleAssignment_5_1(), "rule__CompositeManufacturingStep__ResponsibleAssignment_5_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getInputAssignment_8(), "rule__CompositeManufacturingStep__InputAssignment_8");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getInputAssignment_9_1(), "rule__CompositeManufacturingStep__InputAssignment_9_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getOutputAssignment_13(), "rule__CompositeManufacturingStep__OutputAssignment_13");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getOutputAssignment_14_1(), "rule__CompositeManufacturingStep__OutputAssignment_14_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getContainsAssignment_17(), "rule__CompositeManufacturingStep__ContainsAssignment_17");
			builder.put(grammarAccess.getInputCondition_ImplAccess().getNameAssignment_2(), "rule__InputCondition_Impl__NameAssignment_2");
			builder.put(grammarAccess.getOutputDecisionAccess().getInputAssignment_0(), "rule__OutputDecision__InputAssignment_0");
			builder.put(grammarAccess.getOutputDecisionAccess().getInputAssignment_1_1(), "rule__OutputDecision__InputAssignment_1_1");
			builder.put(grammarAccess.getOutputDecisionAccess().getOutputTypesAssignment_3(), "rule__OutputDecision__OutputTypesAssignment_3");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getNameAssignment_1(), "rule__WorkPieceCondition__NameAssignment_1");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getRequiresTypeAssignment_3(), "rule__WorkPieceCondition__RequiresTypeAssignment_3");
			builder.put(grammarAccess.getBinaryConditionAccess().getNameAssignment_1(), "rule__BinaryCondition__NameAssignment_1");
			builder.put(grammarAccess.getBinaryConditionAccess().getLeftAssignment_3(), "rule__BinaryCondition__LeftAssignment_3");
			builder.put(grammarAccess.getBinaryConditionAccess().getTypeAssignment_4(), "rule__BinaryCondition__TypeAssignment_4");
			builder.put(grammarAccess.getBinaryConditionAccess().getRightAssignment_5(), "rule__BinaryCondition__RightAssignment_5");
			builder.put(grammarAccess.getNegationAccess().getContainsAssignment_1(), "rule__Negation__ContainsAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MSDslGrammarAccess grammarAccess;

	@Override
	protected InternalMSDslParser createParser() {
		InternalMSDslParser result = new InternalMSDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MSDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MSDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
