/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.assignment3.msdsl.ui.AbstractMSDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MSDslUiModule extends AbstractMSDslUiModule {
  public MSDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
