/*
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MSDslScopeProvider extends AbstractMSDslScopeProvider {

}
