/**
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl.ui.contentassist;

import org.xtext.assignment3.msdsl.ui.contentassist.AbstractMSDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MSDslProposalProvider extends AbstractMSDslProposalProvider {
}
