/*
 * generated by Xtext 2.19.0
 */
package org.xtext.assignment3.msdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MSDslRuntimeModule extends AbstractMSDslRuntimeModule {
}
